### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [0xInfection/SIPTorch#2]
I want to understand this script for scanning sip and svwar and crack like the sipvicious or what he will do ?

**Comment by 0xInfection** [comment]
As stated in the README, it is SIP Torture testing suite. It is a series of trials intended to test the stability of SIP parsers (like SBCs), proxies, servers, etc. Please refer to RFC 4475 (https://tools.ietf.org/html/rfc4475) for more information.

@VoipSip I hope this has answered your query.
